name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://oskarstark/php-cs-fixer-ga

  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          # - "7.2-5.6"
          # - "7.2-5.8"
          - "7.2-6"
          # - "7.3-5.6"
          - "7.3-5.8"
          - "7.3-6"
          - "7.3-7"
          - "7.4-6"
          - "7.4-7"
          - "7.4-8"
          - "8.0-6"
          - "8.0-7"
          - "8.0-8"

    steps:
      - uses: actions/checkout@v2

      - name: Set up composer.json
        id: composer
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const composer = require('./composer.json');
            const [php, laravel] = '${{ matrix.versions }}'.split('-');

            composer.require['php'] = '~'.concat(php);
            composer.require['laravel/framework'] = '~'.concat(laravel);

            if (laravel.startsWith('5')) {
              const laravelMinor = laravel.split('.')[1] || '5';
              composer['require-dev']['orchestra/testbench'] = '~3.'+laravelMinor;
              composer['require-dev']['phpunit/phpunit'] = laravelMinor === '5' ? '~6.0' : '^7.5';
            } else if (laravel.startsWith('6')) {
              composer['require-dev']['orchestra/testbench'] = '~4';
              composer['require-dev']['phpunit/phpunit'] = '~8';
            } else if (laravel.startsWith('7')) {
              composer['require-dev']['orchestra/testbench'] = '~5';
              composer['require-dev']['phpunit/phpunit'] = '~9';
            } else if (laravel.startsWith('8')) {
              composer['require-dev']['orchestra/testbench'] = '~6';
              composer['require-dev']['phpunit/phpunit'] = '~9';
            }

            return JSON.stringify(composer);

      - name: Set up PHP version
        id: php
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const [php] = '${{ matrix.versions }}'.split('-');
            return php;

      - name: Rewrite composer.json
        run: |
          rm composer.json
          echo '${{ steps.composer.outputs.result }}' > composer.json
          cat composer.json

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ steps.php.outputs.result }}

      - uses: php-actions/phpunit@v3
