name: CI

on: [push]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://oskarstark/php-cs-fixer-ga

  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.4, 8.0]

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - uses: php-actions/phpunit@v3
