name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://oskarstark/php-cs-fixer-ga

  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - "8.0-6"
          - "8.0-7"
          - "8.0-8"
          - "8.1-6"
          - "8.1-7"
          - "8.1-8"
          - "8.1-9"

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHPUnit version
        id: phpunit
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const [php, laravel] = '${{ matrix.versions }}'.split('-');
            return laravel.startsWith("6")
                ? "8"
                : "9";

      - name: Set up PHP version
        id: php
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const [php] = '${{ matrix.versions }}'.split('-');
            return php;

      - name: Update composer.json
        id: composer
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const composer = require('./composer.json');
            const [php, laravel] = '${{ matrix.versions }}'.split('-');

            composer.require['php'] = '~'.concat(php);
            composer.require['laravel/framework'] = '~'.concat(laravel);
            composer['require-dev']['phpunit/phpunit'] = '~${{ steps.phpunit.outputs.result }}';

            if (laravel.startsWith('5')) {
              composer['require-dev']['orchestra/testbench'] = '~3.'+laravel.split('.')[1] || '5';
            } else {
              const version = parseInt(laravel.split('.')[0], 10);
              composer['require-dev']['orchestra/testbench'] = '~'.concat(version-2);
            }

            return JSON.stringify(composer);

      - name: Rewrite composer.json
        run: |
          rm composer.json
          echo '${{ steps.composer.outputs.result }}' > composer.json
          cat composer.json

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ steps.php.outputs.result }}

      - uses: php-actions/phpunit@v3
        with:
          version: ${{ steps.phpunit.outputs.result }}
          php_version: ${{ steps.php.outputs.result }}
